[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_toh5y5d"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_adio3fd"
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY = "mXppsONCDlpPFSzKf"
  RESEND_API_KEY = "re_PinRmaz2_KRdhkX2cLUiXVxRgmD15yrwL"
  FROM_EMAIL = "bhargavkatkam0@gmail.com"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 